name       : kio
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/kio-5.25.0.tar.xz : d9806d74d0119ced246446fd22110ba8ae5a980e4734b165819b30bcadf90578
license    : LGPL-2.1
component  : desktop.library
summary    : Network transparent access to files and data.
description: |
    Network transparent access to files and data.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - karchive-devel
    - kauth-devel
    - kbookmarks-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - solid-devel
    - sonnet-devel
setup      : |
    %cmake -DBUILD_TESTING=FALSE \
           -DCMAKE_INSTALL_LIBEXECDIR=%libdir% .
build      : |
    %make
install    : |
    %make_install
