name       : kio
version    : 5.84.0
release    : 69
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.84/kio-5.84.0.tar.xz : 96be2b732faf97a484edc5238049ad22f0f233b9e404468f4da40c5ec839e0d3
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Network transparent access to files and data.
description: |
    Network transparent access to files and data.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libacl)
    - pkgconfig(com_err)
    - pkgconfig(libxslt)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(x11)
    - karchive-devel
    - kbookmarks-devel
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kded-devel
    - kdoctools-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - solid-devel
    - sonnet-devel
rundeps    :
    - kded
    - devel :
        - kbookmarks-devel
        - kcompletion-devel
        - ki18n-devel
        - kitemviews-devel
        - kjobwidgets-devel
        - kservice-devel
        - kwindowsystem-devel
        - kxmlgui-devel
        - solid-devel
setup      : |
    %apply_patches
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/HTML
