name       : kio
version    : 5.80.1
release    : 63
source     :
    - https://download.kde.org/stable/frameworks/5.80/kio-5.80.1.tar.xz : d971ce61a022f9e4d2d6be9c66917be271d0fb212795a151150e208e64cd5a28
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Network transparent access to files and data.
description: |
    Network transparent access to files and data.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libacl)
    - pkgconfig(com_err)
    - pkgconfig(libxslt)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(x11)
    - karchive-devel
    - kbookmarks-devel
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kded-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - solid-devel
    - sonnet-devel
rundeps    :
    #- kinit
        - kded
        - devel :
            - kbookmarks-devel
            - kcompletion-devel
            - ki18n-devel
            - kitemviews-devel
            - kjobwidgets-devel
            - kservice-devel
            - kwindowsystem-devel
            - kxmlgui-devel
            - solid-devel
setup      : |
    %patch -p1 -i $pkgfiles/0001-Include-stateless-samba-directory.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/HTML
