name       : kio
version    : 5.75.0
release    : 56
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/kio-5.75.0.tar.xz : 27af8d83d0ea6c68fc62675a0d0d34e94489e9e518c4a4c32fa9d4784510bc8e
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.library
optimize   : lto
summary    : Network transparent access to files and data.
description: |
    Network transparent access to files and data.
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig(libxslt)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - acl-devel
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kded-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - solid-devel
rundeps    :
    - kinit
    - devel :
        - kbookmarks-devel
        - kcompletion-devel
        - kconfig-devel
        - kcoreaddons-devel
        - kitemviews-devel
        - kjobwidgets-devel
        - kservice-devel
        - kxmlgui-devel
        - solid-devel
setup      : |
    %patch -p1 -i $pkgfiles/0001-Include-stateless-samba-directory.patch
    %patch -p1 -i $pkgfiles/0002-fixing-regression.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/HTML
