name       : kio
version    : 5.32.0
release    : 7
source     :
    - http://download.kde.org/stable/frameworks/5.32/kio-5.32.0.tar.xz : 364adf30d1df6f52d5960061d4c21e91519dfa8674ae95fa01144805a800aaa5
license    : LGPL-2.1
component  : desktop.library
summary    : Network transparent access to files and data.
description: |
    Network transparent access to files and data.
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig(gl)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5X11Extras)
    - acl-devel
    - attr-devel
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - solid-devel
rundeps    :
    - kinit
    - devel :
        - kbookmarks-devel
        - kcompletion-devel
        - kconfig-devel
        - kcoreaddons-devel
        - kitemviews-devel
        - kjobwidgets-devel
        - kservice-devel
        - kxmlgui-devel
        - solid-devel
setup      : |
    %cmake -DBUILD_TESTING=FALSE .
build      : |
    %make
install    : |
    %make_install
