name       : kio
version    : 5.65.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/kio-5.65.0.tar.xz : 7d3cc0c82e83c082b424a2fe4c796c4c46f233ccd565775babbf6b434fce851b
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Network transparent access to files and data.
description: |
    Network transparent access to files and data.
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig(libxslt)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - acl-devel
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - solid-devel
rundeps    :
    - kinit
    - devel :
        - kbookmarks-devel
        - kcompletion-devel
        - kconfig-devel
        - kcoreaddons-devel
        - kitemviews-devel
        - kjobwidgets-devel
        - kservice-devel
        - kxmlgui-devel
        - solid-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Include-stateless-samba-directory.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
