name       : kio
version    : 5.51.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.51/kio-5.51.0.tar.xz : c083dfb537e50f143770f0b50665da3779969ee3a1e38ba08e6ed3cc5c921cc7
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Network transparent access to files and data.
description: |
    Network transparent access to files and data.
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig(libxslt)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - acl-devel
    - attr-devel
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - solid-devel
rundeps    :
    - kinit
    - devel :
        - kbookmarks-devel
        - kcompletion-devel
        - kconfig-devel
        - kcoreaddons-devel
        - kitemviews-devel
        - kjobwidgets-devel
        - kservice-devel
        - kxmlgui-devel
        - solid-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Include-stateless-samba-directory.patch
    %patch -p1 < $pkgfiles/Fix-crash-in-QCoreApplication.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
