name       : kio
version    : 5.44.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kio-5.44.0.tar.xz : 7a8fc6f0af101c4a16270d328806fbf96ee8855e756b033d6a08ce744e7071b7
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Network transparent access to files and data.
description: |
    Network transparent access to files and data.
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - acl-devel
    - attr-devel
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - solid-devel
rundeps    :
    - kinit
    - devel :
        - kbookmarks-devel
        - kcompletion-devel
        - kconfig-devel
        - kcoreaddons-devel
        - kitemviews-devel
        - kjobwidgets-devel
        - kservice-devel
        - kxmlgui-devel
        - solid-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-standard-directories-as-default-places.patch
    %patch -p1 < $pkgfiles/0001-Include-stateless-samba-directory.patch
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
