name       : kio
version    : 5.79.0
release    : 62
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/kio-5.79.0.tar.xz : 767c67aab4e1a43d1d2ebf74f9deab21791150cc5f533be561dc1346d16e25e6
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Network transparent access to files and data.
description: |
    Network transparent access to files and data.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libacl)
    - pkgconfig(com_err)
    - pkgconfig(libxslt)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(x11)
    - karchive-devel
    - kbookmarks-devel
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kded-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - solid-devel
    - sonnet-devel
rundeps    :
    #- kinit
    - kded
    - devel :
        - kbookmarks-devel
        - kcompletion-devel
        - ki18n-devel
        - kitemviews-devel
        - kjobwidgets-devel
        - kservice-devel
        - kwindowsystem-devel
        - kxmlgui-devel
        - solid-devel
setup      : |
    %patch -p1 -i $pkgfiles/0001-Include-stateless-samba-directory.patch
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc/HTML
