name       : kio
version    : 5.40.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/kio-5.40.0.tar.xz : 30ea0b231b995faaf4283b9c9ecfaffb589268f5d7b5b805f69ed95601ac389b
license    : LGPL-2.1
component  : desktop.library
summary    : Network transparent access to files and data.
description: |
    Network transparent access to files and data.
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(krb5-gssapi)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5X11Extras)
    - acl-devel
    - attr-devel
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - solid-devel
rundeps    :
    - kinit
    - devel :
        - kbookmarks-devel
        - kcompletion-devel
        - kconfig-devel
        - kcoreaddons-devel
        - kitemviews-devel
        - kjobwidgets-devel
        - kservice-devel
        - kxmlgui-devel
        - solid-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-standard-directories-as-default-places.patch
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
